[package]
name = "namaco"
version = "0.1.0"
authors = ["namachan10777 <namachan10777@gmail.com>"]
edition = "2018"

[dependencies]
rust-crypto = "*"

[profile.bench]
debug = true
[profile.release]
debug = true
